/**
 * KAUSHAL DRISHTI — Phase 2 Data Provider Abstraction
 * ---------------------------------------------------------------------
 * Provider interfaces. Phase 2 implements:
 *   - SyntheticDataProvider (the seed)
 *   - CSVDataProvider        (CSV upload)
 *   - JSONDataProvider       (JSON upload)
 *   - ManualEntryProvider    (admin form)
 *
 * Future official API/connectors (OfficialGovernmentProvider, APIProvider,
 * CSVProvider, PartnerProvider) plug into the same interface without
 * rewriting the ingestion pipeline.
 */
import { parseUpload } from "./parser";

export interface IngestionSource {
  sourceId: string;
  sourceType: string;
  dataStatus: string;
  providerName: string;
}

export interface RawRecordBatch {
  source: IngestionSource;
  records: Record<string, unknown>[];
  fileType: "csv" | "json" | "synthetic" | "manual";
  fileName?: string;
}

export interface DataProvider {
  name: string;
  /** Fetch records from the provider into a uniform raw batch. */
  fetch(): Promise<RawRecordBatch>;
}

/** CSV provider: wraps parsed CSV text into a raw batch. */
export class CSVDataProvider implements DataProvider {
  name = "CSVDataProvider";
  constructor(
    private readonly csvText: string,
    private readonly source: IngestionSource,
    private readonly fileName?: string,
  ) {}
  async fetch(): Promise<RawRecordBatch> {
    const parsed = parseUpload(this.csvText, "csv");
    return {
      source: this.source,
      records: parsed.records,
      fileType: "csv",
      fileName: this.fileName,
    };
  }
}

/** JSON provider: wraps parsed JSON text into a raw batch. */
export class JSONDataProvider implements DataProvider {
  name = "JSONDataProvider";
  constructor(
    private readonly jsonText: string,
    private readonly source: IngestionSource,
    private readonly fileName?: string,
  ) {}
  async fetch(): Promise<RawRecordBatch> {
    const parsed = parseUpload(this.jsonText, "json");
    return {
      source: this.source,
      records: parsed.records,
      fileType: "json",
      fileName: this.fileName,
    };
  }
}

/** Manual entry provider: in-memory records from admin form. */
export class ManualEntryProvider implements DataProvider {
  name = "ManualEntryProvider";
  constructor(
    private readonly records: Record<string, unknown>[],
    private readonly source: IngestionSource,
  ) {}
  async fetch(): Promise<RawRecordBatch> {
    return { source: this.source, records: this.records, fileType: "manual" };
  }
}

/** Synthetic provider: in-memory records generated by the seed. */
export class SyntheticDataProvider implements DataProvider {
  name = "SyntheticDataProvider";
  constructor(
    private readonly records: Record<string, unknown>[],
    private readonly source: IngestionSource,
  ) {}
  async fetch(): Promise<RawRecordBatch> {
    return { source: this.source, records: this.records, fileType: "synthetic" };
  }
}
